name: lastminute
description: "Because Deadlines Always Sneak Up"
publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.2.1
  http: ^1.2.2

  # UI & Calendar
  table_calendar: ^3.1.2
  intl: ^0.20.2
  google_fonts: ^7.0.2

  # Notifications & Scheduling
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  # Platform-specific (Android calendar & study mode)
  device_calendar: ^4.3.2
  app_usage: ^4.0.1
  shared_preferences: ^2.3.4
  installed_apps: ^2.1.0
  flutter_overlay_window: ^0.5.0
  wakelock_plus: ^1.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
